# Generated by Django 3.1 on 2020-08-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20200816_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='title',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
